// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: error/error.proto

package error

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReasonCode int32

const (
	// 通用錯誤原因代碼: 0 ~ 999
	// 當不需要太細緻的錯誤原因時，可以直接使用這些代碼
	ErrorReasonCode_ERR_COMMON_INTERNAL                         ErrorReasonCode = 0
	ErrorReasonCode_ERR_COMMON_INVALID_ARGUMENT                 ErrorReasonCode = 1
	ErrorReasonCode_ERR_NOTIFY_INVALID_RECEIVER                 ErrorReasonCode = 1000
	ErrorReasonCode_ERR_NOTIFY_RECEIVER_EMPTY                   ErrorReasonCode = 1001
	ErrorReasonCode_ERR_NOTIFY_SUBJECT_EMPTY                    ErrorReasonCode = 1002
	ErrorReasonCode_ERR_NOTIFY_BODY_EMPTY                       ErrorReasonCode = 1003
	ErrorReasonCode_ERR_NOTIFY_MESSAGE_NOT_FOUND                ErrorReasonCode = 1004
	ErrorReasonCode_ERR_NOTIFY_MESSAGE_IS_ENQUEUE_CANNOT_CANCEL ErrorReasonCode = 1005
)

// Enum value maps for ErrorReasonCode.
var (
	ErrorReasonCode_name = map[int32]string{
		0:    "ERR_COMMON_INTERNAL",
		1:    "ERR_COMMON_INVALID_ARGUMENT",
		1000: "ERR_NOTIFY_INVALID_RECEIVER",
		1001: "ERR_NOTIFY_RECEIVER_EMPTY",
		1002: "ERR_NOTIFY_SUBJECT_EMPTY",
		1003: "ERR_NOTIFY_BODY_EMPTY",
		1004: "ERR_NOTIFY_MESSAGE_NOT_FOUND",
		1005: "ERR_NOTIFY_MESSAGE_IS_ENQUEUE_CANNOT_CANCEL",
	}
	ErrorReasonCode_value = map[string]int32{
		"ERR_COMMON_INTERNAL":                         0,
		"ERR_COMMON_INVALID_ARGUMENT":                 1,
		"ERR_NOTIFY_INVALID_RECEIVER":                 1000,
		"ERR_NOTIFY_RECEIVER_EMPTY":                   1001,
		"ERR_NOTIFY_SUBJECT_EMPTY":                    1002,
		"ERR_NOTIFY_BODY_EMPTY":                       1003,
		"ERR_NOTIFY_MESSAGE_NOT_FOUND":                1004,
		"ERR_NOTIFY_MESSAGE_IS_ENQUEUE_CANNOT_CANCEL": 1005,
	}
)

func (x ErrorReasonCode) Enum() *ErrorReasonCode {
	p := new(ErrorReasonCode)
	*p = x
	return p
}

func (x ErrorReasonCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReasonCode) Descriptor() protoreflect.EnumDescriptor {
	return file_error_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReasonCode) Type() protoreflect.EnumType {
	return &file_error_error_proto_enumTypes[0]
}

func (x ErrorReasonCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReasonCode.Descriptor instead.
func (ErrorReasonCode) EnumDescriptor() ([]byte, []int) {
	return file_error_error_proto_rawDescGZIP(), []int{0}
}

var File_error_error_proto protoreflect.FileDescriptor

const file_error_error_proto_rawDesc = "" +
	"\n" +
	"\x11error/error.proto\x12\x0fnotify.v1.error*\x9d\x02\n" +
	"\x0fErrorReasonCode\x12\x17\n" +
	"\x13ERR_COMMON_INTERNAL\x10\x00\x12\x1f\n" +
	"\x1bERR_COMMON_INVALID_ARGUMENT\x10\x01\x12 \n" +
	"\x1bERR_NOTIFY_INVALID_RECEIVER\x10\xe8\a\x12\x1e\n" +
	"\x19ERR_NOTIFY_RECEIVER_EMPTY\x10\xe9\a\x12\x1d\n" +
	"\x18ERR_NOTIFY_SUBJECT_EMPTY\x10\xea\a\x12\x1a\n" +
	"\x15ERR_NOTIFY_BODY_EMPTY\x10\xeb\a\x12!\n" +
	"\x1cERR_NOTIFY_MESSAGE_NOT_FOUND\x10\xec\a\x120\n" +
	"+ERR_NOTIFY_MESSAGE_IS_ENQUEUE_CANNOT_CANCEL\x10\xed\aB\x1bZ\x19proto/pkg/notify/v1/errorb\x06proto3"

var (
	file_error_error_proto_rawDescOnce sync.Once
	file_error_error_proto_rawDescData []byte
)

func file_error_error_proto_rawDescGZIP() []byte {
	file_error_error_proto_rawDescOnce.Do(func() {
		file_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_error_proto_rawDesc), len(file_error_error_proto_rawDesc)))
	})
	return file_error_error_proto_rawDescData
}

var file_error_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_error_proto_goTypes = []any{
	(ErrorReasonCode)(0), // 0: notify.v1.error.ErrorReasonCode
}
var file_error_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_error_proto_init() }
func file_error_error_proto_init() {
	if File_error_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_error_proto_rawDesc), len(file_error_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_error_proto_goTypes,
		DependencyIndexes: file_error_error_proto_depIdxs,
		EnumInfos:         file_error_error_proto_enumTypes,
	}.Build()
	File_error_error_proto = out.File
	file_error_error_proto_goTypes = nil
	file_error_error_proto_depIdxs = nil
}
