// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: notify/notify.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// 訊息類型枚舉
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_SMS                      MessageType = 1
	MessageType_MAIL                     MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "SMS",
		2: "MAIL",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"SMS":                      1,
		"MAIL":                     2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_notify_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_notify_notify_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{0}
}

// *
// 簡訊
type Sms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"` // 簡訊內容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sms) Reset() {
	*x = Sms{}
	mi := &file_notify_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{0}
}

func (x *Sms) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// *
// 發送簡訊請求
type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sms           *Sms                   `protobuf:"bytes,1,opt,name=sms,proto3" json:"sms,omitempty"`                                    // 簡訊
	Receivers     []string               `protobuf:"bytes,2,rep,name=receivers,proto3" json:"receivers,omitempty"`                        // 收件者手機號碼
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // 預約時間（限制30天內，可選填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_notify_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsRequest) GetSms() *Sms {
	if x != nil {
		return x.Sms
	}
	return nil
}

func (x *SendSmsRequest) GetReceivers() []string {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *SendSmsRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

// *
// 發送簡訊響應
type SendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 訊息 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResponse) Reset() {
	*x = SendSmsResponse{}
	mi := &file_notify_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResponse) ProtoMessage() {}

func (x *SendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResponse.ProtoReflect.Descriptor instead.
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{2}
}

func (x *SendSmsResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// *
// 郵件
type Mail struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SenderAddress *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"` // 寄件者電子郵件地址
	SenderName    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`          // 寄件者名稱
	Subject       string                  `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`                                  // 郵件主旨
	Body          string                  `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`                                        // 郵件內容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mail) Reset() {
	*x = Mail{}
	mi := &file_notify_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{3}
}

func (x *Mail) GetSenderAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.SenderAddress
	}
	return nil
}

func (x *Mail) GetSenderName() *wrapperspb.StringValue {
	if x != nil {
		return x.SenderName
	}
	return nil
}

func (x *Mail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Mail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// *
// 發送郵件請求
type SendMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mail          *Mail                  `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`                                  // 郵件資訊
	Receivers     []string               `protobuf:"bytes,2,rep,name=receivers,proto3" json:"receivers,omitempty"`                        // 收件者電子郵件地址
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"` // 預約時間（限制30天內，可選填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_notify_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{4}
}

func (x *SendMailRequest) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *SendMailRequest) GetReceivers() []string {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *SendMailRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

// *
// 發送郵件響應
type SendMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 訊息 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailResponse) Reset() {
	*x = SendMailResponse{}
	mi := &file_notify_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailResponse) ProtoMessage() {}

func (x *SendMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailResponse.ProtoReflect.Descriptor instead.
func (*SendMailResponse) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{5}
}

func (x *SendMailResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// *
// 取消預約訊息請求
type CancelScheduledByMessageIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 訊息 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScheduledByMessageIdRequest) Reset() {
	*x = CancelScheduledByMessageIdRequest{}
	mi := &file_notify_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScheduledByMessageIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScheduledByMessageIdRequest) ProtoMessage() {}

func (x *CancelScheduledByMessageIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScheduledByMessageIdRequest.ProtoReflect.Descriptor instead.
func (*CancelScheduledByMessageIdRequest) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{6}
}

func (x *CancelScheduledByMessageIdRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// *
// 分頁請求資訊
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                         // 當前分頁索引
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                           // 每頁筆數
	SortField     string                 `protobuf:"bytes,3,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"` // 排序欄位
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // 排序方向（ASC 或 DESC）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_notify_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{7}
}

func (x *PageRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PageRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PageRequest) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *PageRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// *
// 查詢發送狀態請求（支持分頁）
type ListStatusWithPagingRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MessageType MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=notify.v1.MessageType" json:"message_type,omitempty"` // 訊息類型（SMS 或 MAIL）
	// Types that are valid to be assigned to Query:
	//
	//	*ListStatusWithPagingRequest_MessageId
	//	*ListStatusWithPagingRequest_Receiver
	Query         isListStatusWithPagingRequest_Query `protobuf_oneof:"query"`
	Page          *PageRequest                        `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`                      // 分頁請求資訊
	StartAt       *timestamppb.Timestamp              `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"` // 起始時間（限制90天內）
	EndAt         *timestamppb.Timestamp              `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`       // 結束時間（限制90天內）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatusWithPagingRequest) Reset() {
	*x = ListStatusWithPagingRequest{}
	mi := &file_notify_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatusWithPagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatusWithPagingRequest) ProtoMessage() {}

func (x *ListStatusWithPagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatusWithPagingRequest.ProtoReflect.Descriptor instead.
func (*ListStatusWithPagingRequest) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{8}
}

func (x *ListStatusWithPagingRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ListStatusWithPagingRequest) GetQuery() isListStatusWithPagingRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ListStatusWithPagingRequest) GetMessageId() string {
	if x != nil {
		if x, ok := x.Query.(*ListStatusWithPagingRequest_MessageId); ok {
			return x.MessageId
		}
	}
	return ""
}

func (x *ListStatusWithPagingRequest) GetReceiver() string {
	if x != nil {
		if x, ok := x.Query.(*ListStatusWithPagingRequest_Receiver); ok {
			return x.Receiver
		}
	}
	return ""
}

func (x *ListStatusWithPagingRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListStatusWithPagingRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *ListStatusWithPagingRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type isListStatusWithPagingRequest_Query interface {
	isListStatusWithPagingRequest_Query()
}

type ListStatusWithPagingRequest_MessageId struct {
	MessageId string `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3,oneof"` // 訊息 ID
}

type ListStatusWithPagingRequest_Receiver struct {
	Receiver string `protobuf:"bytes,3,opt,name=receiver,proto3,oneof"` // 收件者手機號碼或電子郵件地址
}

func (*ListStatusWithPagingRequest_MessageId) isListStatusWithPagingRequest_Query() {}

func (*ListStatusWithPagingRequest_Receiver) isListStatusWithPagingRequest_Query() {}

// *
// 發送記錄資訊
type Target struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageType    string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`          // 訊息類型（SMS 或 MAIL）
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                // 訊息 ID
	MessageContent string                 `protobuf:"bytes,3,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 訊息內容（文字 或 HTML）
	Receiver       string                 `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`                                   // 收件者（手機號碼或電子郵件地址）
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                       // 寄送狀態
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // 建立時間
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                // 更新時間
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_notify_notify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{9}
}

func (x *Target) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Target) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Target) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *Target) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Target) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Target) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Target) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// *
// 分頁資訊響應結構
type Paging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	SortField     string                 `protobuf:"bytes,4,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"` // 排序欄位
	SortOrder     string                 `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // 排序方向（ASC 或 DESC）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paging) Reset() {
	*x = Paging{}
	mi := &file_notify_notify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paging) ProtoMessage() {}

func (x *Paging) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paging.ProtoReflect.Descriptor instead.
func (*Paging) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{10}
}

func (x *Paging) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Paging) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Paging) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Paging) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *Paging) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// *
// 查詢發送狀態響應
type ListStatusWithPagingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        []*Target              `protobuf:"bytes,1,rep,name=target,proto3" json:"target,omitempty"` // 訊息發送紀錄
	Paging        *Paging                `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"` // 分頁資訊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatusWithPagingResponse) Reset() {
	*x = ListStatusWithPagingResponse{}
	mi := &file_notify_notify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatusWithPagingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatusWithPagingResponse) ProtoMessage() {}

func (x *ListStatusWithPagingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_notify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatusWithPagingResponse.ProtoReflect.Descriptor instead.
func (*ListStatusWithPagingResponse) Descriptor() ([]byte, []int) {
	return file_notify_notify_proto_rawDescGZIP(), []int{11}
}

func (x *ListStatusWithPagingResponse) GetTarget() []*Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ListStatusWithPagingResponse) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

var File_notify_notify_proto protoreflect.FileDescriptor

const file_notify_notify_proto_rawDesc = "" +
	"\n" +
	"\x13notify/notify.proto\x12\tnotify.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x19\n" +
	"\x03Sms\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"\x8f\x01\n" +
	"\x0eSendSmsRequest\x12 \n" +
	"\x03sms\x18\x01 \x01(\v2\x0e.notify.v1.SmsR\x03sms\x12\x1c\n" +
	"\treceivers\x18\x02 \x03(\tR\treceivers\x12=\n" +
	"\fscheduled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"0\n" +
	"\x0fSendSmsResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xb8\x01\n" +
	"\x04Mail\x12C\n" +
	"\x0esender_address\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\rsenderAddress\x12=\n" +
	"\vsender_name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"senderName\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\"\x93\x01\n" +
	"\x0fSendMailRequest\x12#\n" +
	"\x04mail\x18\x01 \x01(\v2\x0f.notify.v1.MailR\x04mail\x12\x1c\n" +
	"\treceivers\x18\x02 \x03(\tR\treceivers\x12=\n" +
	"\fscheduled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"1\n" +
	"\x10SendMailResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"B\n" +
	"!CancelScheduledByMessageIdRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"u\n" +
	"\vPageRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x03 \x01(\tR\tsortField\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"\xb6\x02\n" +
	"\x1bListStatusWithPagingRequest\x129\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x16.notify.v1.MessageTypeR\vmessageType\x12\x1f\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tH\x00R\tmessageId\x12\x1c\n" +
	"\breceiver\x18\x03 \x01(\tH\x00R\breceiver\x12*\n" +
	"\x04page\x18\x04 \x01(\v2\x16.notify.v1.PageRequestR\x04page\x125\n" +
	"\bstart_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAtB\a\n" +
	"\x05query\"\x9d\x02\n" +
	"\x06Target\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12'\n" +
	"\x0fmessage_content\x18\x03 \x01(\tR\x0emessageContent\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\tR\breceiver\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x86\x01\n" +
	"\x06Paging\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x04 \x01(\tR\tsortField\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tR\tsortOrder\"t\n" +
	"\x1cListStatusWithPagingResponse\x12)\n" +
	"\x06target\x18\x01 \x03(\v2\x11.notify.v1.TargetR\x06target\x12)\n" +
	"\x06paging\x18\x02 \x01(\v2\x11.notify.v1.PagingR\x06paging*>\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03SMS\x10\x01\x12\b\n" +
	"\x04MAIL\x10\x022\xfc\x03\n" +
	"\rNotifyService\x12@\n" +
	"\aSendSms\x12\x19.notify.v1.SendSmsRequest\x1a\x1a.notify.v1.SendSmsResponse\x12I\n" +
	"\fSendBatchSms\x12\x19.notify.v1.SendSmsRequest\x1a\x1a.notify.v1.SendSmsResponse(\x010\x01\x12C\n" +
	"\bSendMail\x12\x1a.notify.v1.SendMailRequest\x1a\x1b.notify.v1.SendMailResponse\x12L\n" +
	"\rSendBatchMail\x12\x1a.notify.v1.SendMailRequest\x1a\x1b.notify.v1.SendMailResponse(\x010\x01\x12b\n" +
	"\x1aCancelScheduledByMessageId\x12,.notify.v1.CancelScheduledByMessageIdRequest\x1a\x16.google.protobuf.Empty\x12g\n" +
	"\x14ListStatusWithPaging\x12&.notify.v1.ListStatusWithPagingRequest\x1a'.notify.v1.ListStatusWithPagingResponseB\x15Z\x13proto/pkg/notify/v1b\x06proto3"

var (
	file_notify_notify_proto_rawDescOnce sync.Once
	file_notify_notify_proto_rawDescData []byte
)

func file_notify_notify_proto_rawDescGZIP() []byte {
	file_notify_notify_proto_rawDescOnce.Do(func() {
		file_notify_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_notify_proto_rawDesc), len(file_notify_notify_proto_rawDesc)))
	})
	return file_notify_notify_proto_rawDescData
}

var file_notify_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notify_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_notify_notify_proto_goTypes = []any{
	(MessageType)(0),                          // 0: notify.v1.MessageType
	(*Sms)(nil),                               // 1: notify.v1.Sms
	(*SendSmsRequest)(nil),                    // 2: notify.v1.SendSmsRequest
	(*SendSmsResponse)(nil),                   // 3: notify.v1.SendSmsResponse
	(*Mail)(nil),                              // 4: notify.v1.Mail
	(*SendMailRequest)(nil),                   // 5: notify.v1.SendMailRequest
	(*SendMailResponse)(nil),                  // 6: notify.v1.SendMailResponse
	(*CancelScheduledByMessageIdRequest)(nil), // 7: notify.v1.CancelScheduledByMessageIdRequest
	(*PageRequest)(nil),                       // 8: notify.v1.PageRequest
	(*ListStatusWithPagingRequest)(nil),       // 9: notify.v1.ListStatusWithPagingRequest
	(*Target)(nil),                            // 10: notify.v1.Target
	(*Paging)(nil),                            // 11: notify.v1.Paging
	(*ListStatusWithPagingResponse)(nil),      // 12: notify.v1.ListStatusWithPagingResponse
	(*timestamppb.Timestamp)(nil),             // 13: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),            // 14: google.protobuf.StringValue
	(*emptypb.Empty)(nil),                     // 15: google.protobuf.Empty
}
var file_notify_notify_proto_depIdxs = []int32{
	1,  // 0: notify.v1.SendSmsRequest.sms:type_name -> notify.v1.Sms
	13, // 1: notify.v1.SendSmsRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	14, // 2: notify.v1.Mail.sender_address:type_name -> google.protobuf.StringValue
	14, // 3: notify.v1.Mail.sender_name:type_name -> google.protobuf.StringValue
	4,  // 4: notify.v1.SendMailRequest.mail:type_name -> notify.v1.Mail
	13, // 5: notify.v1.SendMailRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	0,  // 6: notify.v1.ListStatusWithPagingRequest.message_type:type_name -> notify.v1.MessageType
	8,  // 7: notify.v1.ListStatusWithPagingRequest.page:type_name -> notify.v1.PageRequest
	13, // 8: notify.v1.ListStatusWithPagingRequest.start_at:type_name -> google.protobuf.Timestamp
	13, // 9: notify.v1.ListStatusWithPagingRequest.end_at:type_name -> google.protobuf.Timestamp
	13, // 10: notify.v1.Target.created_at:type_name -> google.protobuf.Timestamp
	13, // 11: notify.v1.Target.updated_at:type_name -> google.protobuf.Timestamp
	10, // 12: notify.v1.ListStatusWithPagingResponse.target:type_name -> notify.v1.Target
	11, // 13: notify.v1.ListStatusWithPagingResponse.paging:type_name -> notify.v1.Paging
	2,  // 14: notify.v1.NotifyService.SendSms:input_type -> notify.v1.SendSmsRequest
	2,  // 15: notify.v1.NotifyService.SendBatchSms:input_type -> notify.v1.SendSmsRequest
	5,  // 16: notify.v1.NotifyService.SendMail:input_type -> notify.v1.SendMailRequest
	5,  // 17: notify.v1.NotifyService.SendBatchMail:input_type -> notify.v1.SendMailRequest
	7,  // 18: notify.v1.NotifyService.CancelScheduledByMessageId:input_type -> notify.v1.CancelScheduledByMessageIdRequest
	9,  // 19: notify.v1.NotifyService.ListStatusWithPaging:input_type -> notify.v1.ListStatusWithPagingRequest
	3,  // 20: notify.v1.NotifyService.SendSms:output_type -> notify.v1.SendSmsResponse
	3,  // 21: notify.v1.NotifyService.SendBatchSms:output_type -> notify.v1.SendSmsResponse
	6,  // 22: notify.v1.NotifyService.SendMail:output_type -> notify.v1.SendMailResponse
	6,  // 23: notify.v1.NotifyService.SendBatchMail:output_type -> notify.v1.SendMailResponse
	15, // 24: notify.v1.NotifyService.CancelScheduledByMessageId:output_type -> google.protobuf.Empty
	12, // 25: notify.v1.NotifyService.ListStatusWithPaging:output_type -> notify.v1.ListStatusWithPagingResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_notify_notify_proto_init() }
func file_notify_notify_proto_init() {
	if File_notify_notify_proto != nil {
		return
	}
	file_notify_notify_proto_msgTypes[8].OneofWrappers = []any{
		(*ListStatusWithPagingRequest_MessageId)(nil),
		(*ListStatusWithPagingRequest_Receiver)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_notify_proto_rawDesc), len(file_notify_notify_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_notify_proto_goTypes,
		DependencyIndexes: file_notify_notify_proto_depIdxs,
		EnumInfos:         file_notify_notify_proto_enumTypes,
		MessageInfos:      file_notify_notify_proto_msgTypes,
	}.Build()
	File_notify_notify_proto = out.File
	file_notify_notify_proto_goTypes = nil
	file_notify_notify_proto_depIdxs = nil
}
